title: tandavala's portofolio
author: José Tandavala
email: jose.tandavala@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Backend Engineer, Open Source Enthusiast and I love the idea of solving real-world problems through software.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: José Tandavala
  tagline: Backend Engineer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: tandavala10
    github: tandavala
    linkedIn: in/josetandavala
    youtube: channel/UCY8OWK1kt3D0x0mjXAxUBgw
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
